- name: stain-normalization-1
  import_path: models.stain_normalization:app
  route_prefix: /stain-normalization-1
  runtime_env:
    working_dir: https://github.com/RationAI/model-service/archive/refs/heads/feat/stain-normalization-deploy.zip
  deployments:
    - name: StainNormalization
      max_ongoing_requests: 128
      max_queued_requests: 256
      autoscaling_config:
        min_replicas: 0
        max_replicas: 4
        target_ongoing_requests: 32
      ray_actor_options:
        num_cpus: 4
        num_gpus: 1
        memory: 12884901888 # 12 GiB
        runtime_env:
          env_vars:
            MLFLOW_TRACKING_URI: http://mlflow.rationai-mlflow:5000
      user_config:
        tile_size: 512
        max_batch_size: 24
        batch_wait_timeout_s: 0.05
        intra_op_num_threads: 4
        trt_max_workspace_size: 8589934592
        trt_cache_path: /mnt/cache/trt_cache/stain-normalization-1/b24
        trt_builder_optimization_level: 3
        model:
          _target_: providers.model_provider:mlflow
          artifact_uri: mlflow-artifacts:/79/5a53cd18689e4d7697aa1b4160ded0ed/artifacts/checkpoints/epoch=17-step=135000/model.onnx
