- name: tissue-linear
  import_path: models.tissue_linear:app
  route_prefix: /tissue-linear
  runtime_env:
    config:
      setup_timeout_seconds: 1800
    working_dir: https://github.com/RationAI/model-service/archive/refs/heads/main.zip
  deployments:
    - name: TissueLinear
      max_ongoing_requests: 512
      max_queued_requests: 4096
      autoscaling_config:
        min_replicas: 0
        max_replicas: 2
        target_ongoing_requests: 128
      ray_actor_options:
        num_cpus: 2
        num_gpus: 1
        memory: 12884901888
        runtime_env:
          env_vars:
            MLFLOW_TRACKING_URI: http://mlflow.rationai-mlflow:5000
            HF_HOME: /mnt/huggingface_cache
      user_config:
        tile_size: 224
        output_tile_size: 1
        n_channels: 7
        mpp: 0.5
        max_batch_size: 64
        batch_wait_timeout_s: 0.1
        foundation_model_id: virchow2
        model:
          _target_: providers.model_provider:mlflow
          artifact_uri: mlflow-artifacts:/104/0e2230c722134ce0985e09a18ccadf75/artifacts/onnx/linear_head.onnx
