apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-test-refs-pvc
  labels:
    app: model-service-tests
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
