include:
  project: rationai/digital-pathology/templates/ci-templates
  file: Python-Lint.gitlab-ci.yml

stages:
  - lint
  - docs

docs:build:
  stage: docs
  image: python:3.12
  script:
    - python -m pip install --upgrade pip
    - python -m pip install mkdocs mkdocs-material pymdown-extensions
    - mkdocs build --strict
