apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-xai
spec:
  serveConfigV2: |
    applications:
      - name: nfm-xai
        import_path: xai.nfm.ingress:app
        route_prefix: /
        runtime_env:
          working_dir: https://gitlab.ics.muni.cz/rationai/infrastructure/model-service/-/archive/feature/xai/model-service-feature-xai.zip
        deployments:
          - name: NFM
            max_ongoing_requests: 16
            max_queued_requests: 64
            autoscaling_config:
              min_replicas: 1
              max_replicas: 1
              target_ongoing_requests: 1
            ray_actor_options:
              num_cpus: 12
              num_gpus: 1
              memory: 68719476736 # 64 GiB
              runtime_env:
                pip: ["torch", "transformers", "einops", "torchvision"]

  rayClusterConfig:
    rayVersion: 2.53.0
    enableInTreeAutoscaling: true
    autoscalerOptions:
      idleTimeoutSeconds: 60
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]

    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
        dashboard-host: "0.0.0.0"
      template:
        spec:
          securityContext:
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: ray-head
              image: rayproject/ray:2.53.0-py312
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 0
                  memory: 4Gi
                requests:
                  cpu: 0
                  memory: 4Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
              securityContext:
                runAsUser: 1000
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]

    workerGroupSpecs:
      - groupName: gpu-workers
        replicas: 1
        minReplicas: 1
        maxReplicas: 1
        template:
          spec:
            securityContext:
              fsGroupChangePolicy: OnRootMismatch
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            containers:
              - name: ray-worker
                image: cerit.io/rationai/model-service:2.53.0
                imagePullPolicy: Always
                resources:
                  limits:
                    cpu: 12
                    memory: 64Gi
                    nvidia.com/mig-2g.20gb: 1
                  requests:
                    cpu: 12
                    memory: 64Gi
                env:
                  - name: HTTPS_PROXY
                    value: http://proxy.ics.muni.cz:3128
                  - name: LD_LIBRARY_PATH
                    value: /usr/local/lib
                securityContext:
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop: ["ALL"]
                  runAsUser: 1000
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                volumeMounts:
                  - name: data
                    mountPath: /mnt/data
                  - name: projects
                    mountPath: /mnt/projects

            volumes:
              - name: data
                persistentVolumeClaim:
                  claimName: data-ro
              - name: projects
                persistentVolumeClaim:
                  claimName: projects-rw
