apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-models
spec:
  serveConfigV2: |
    applications:
      - name: LSP-DETR
        import_path: models.lsp_detr:app
        route_prefix: /lsp-detr
        runtime_env:
          working_dir: https://gitlab.ics.muni.cz/rationai/infrastructure/model-service/-/archive/develop/model-service-develop.zip?path=models

  rayClusterConfig:
    rayVersion: 2.49.2
    enableInTreeAutoscaling: true
    autoscalerOptions:
      idleTimeoutSeconds: 60 # number of seconds to wait before scaling down a worker pod which is not using Ray resources.
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]

    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
        dashboard-host: "0.0.0.0"
      template:
        spec:
          securityContext:
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault

          containers:
            - name: ray-head
              image: rayproject/ray:2.49.2-py312
              securityContext:
                runAsUser: 1000
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]
              resources:
                limits:
                  cpu: 0
                  memory: 4Gi
                requests:
                  cpu: 0
                  memory: 4Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve

    workerGroupSpecs:
      - groupName: gpu-group
        minReplicas: 1
        maxReplicas: 2
        template:
          spec:
            securityContext:
              fsGroupChangePolicy: OnRootMismatch
              runAsNonRoot: true
              seccompProfile:
                type: RuntimeDefault
            nodeSelector:
              nvidia.com/gpu.product: NVIDIA-A40
            containers:
              - name: ray-worker
                image: rayproject/ray:2.49.2-py312-gpu
                env:
                  - name: HTTPS_PROXY
                    value: http://proxy.muni.cz:3128
                securityContext:
                  runAsUser: 1000
                  allowPrivilegeEscalation: false
                  capabilities:
                    drop: ["ALL"]
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh", "-c", "ray stop"]
                resources:
                  limits:
                    cpu: 4
                    memory: 10Gi
                    nvidia.com/gpu: 1
                  requests:
                    cpu: 4
                    memory: 10Gi
