applications:
  - name: prostate-classifier-1
    import_path: models.binary_classifier:app
    route_prefix: /prostate-classifier-1
    runtime_env:
      working_dir: https://github.com/RationAI/model-service/archive/refs/heads/main.zip
    deployments:
      - name: BinaryClassifier
        max_ongoing_requests: 512
        max_queued_requests: 1024
        autoscaling_config:
          min_replicas: 0
          max_replicas: 4
          target_ongoing_requests: 128
        ray_actor_options:
          num_cpus: 4
          num_gpus: 1
          memory: 12884901888
          runtime_env:
            env_vars:
              MLFLOW_TRACKING_URI: http://mlflow.rationai-mlflow:5000
        user_config:
          tile_size: 512
          max_batch_size: 256
          batch_wait_timeout_s: 0.05
          intra_op_num_threads: 4
          trt_max_workspace_size: 8589934592
          trt_cache_path: /mnt/cache/trt_cache/binary-classifier-1/b256
          trt_builder_optimization_level: 3
          model:
            _target_: providers.model_provider:mlflow
            artifact_uri: mlflow-artifacts:/65/aebc892f526047249b972f200bef4381/artifacts/checkpoints/epoch=0-step=6972/prostate_model_norm.onnx
