groupName: mig20-gpu-workers
replicas: 0
minReplicas: 0
maxReplicas: 4
rayStartParams:
  num-gpus: "1"
template:
  spec:
    securityContext:
      fsGroup: 1000
      fsGroupChangePolicy: OnRootMismatch
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    containers:
      - name: ray-worker
        image: cerit.io/rationai/model-service:2.54.0-gpu
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 8
            memory: 24Gi
            nvidia.com/mig-2g.20gb: 1
          requests:
            cpu: 8
            memory: 24Gi
        env:
          - name: HTTPS_PROXY
            value: http://proxy.ics.muni.cz:3128
          - name: HF_TOKEN
            valueFrom:
              secretKeyRef:
                name: huggingface-secret
                key: token
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          runAsUser: 1000
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "ray stop"]
        volumeMounts:
          - name: data
            mountPath: /mnt/data
          - name: public-data
            mountPath: /mnt/data/Public
          - name: projects
            mountPath: /mnt/projects
          - name: bioptic-tree
            mountPath: /mnt/bioptic_tree
          - name: trt-cache-volume
            mountPath: /mnt/cache
          - name: huggingface-cache
            mountPath: /mnt/huggingface_cache
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{ .Values.pvcs.data }}
      - name: public-data
        persistentVolumeClaim:
          claimName: {{ .Values.pvcs.publicData }}
      - name: projects
        persistentVolumeClaim:
          claimName: {{ .Values.pvcs.projects }}
      - name: bioptic-tree
        persistentVolumeClaim:
          claimName: {{ .Values.pvcs.biopticTree }}
      - name: trt-cache-volume
        persistentVolumeClaim:
          claimName: {{ .Values.pvcs.tensorrtCache.claimName }}
      - name: huggingface-cache
        persistentVolumeClaim:
          claimName: {{ .Values.pvcs.huggingface.claimName }}
