{{- $base := .Files.Get "files/base/ray-service-base.yaml" | fromYaml -}}
apiVersion: {{ $base.apiVersion }}
kind: {{ $base.kind }}
metadata:
{{- toYaml $base.metadata | nindent 2 }}
spec:
  rayClusterConfig:
{{- toYaml (omit $base.spec.rayClusterConfig "workerGroupSpecs") | nindent 4 }}
    workerGroupSpecs:
{{- range $workerName := .Values.workers.enabled }}
{{- $workerContent := printf "files/workers/%s.yaml" $workerName | $.Files.Get | fromYaml }}
      - {{ toYaml $workerContent | nindent 8 | trim }}
{{- end }}
  serveConfigV2: |
    applications:
{{- range $appName := .Values.applications.enabled }}
{{ printf "files/applications/%s.yaml" $appName | $.Files.Get | indent 4 }}
{{- end }}