apiVersion: batch/v1
kind: Job
metadata:
  name: virchow-downloader
  namespace: rationai-jobs-ns
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: downloader
          image: python:3.12
          resources:
            requests:
              memory: "4Gi"
              cpu: "1"
            limits:
              memory: "4Gi"
              cpu: "2"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          command: ["/bin/bash", "-c"]
          args:
            - |
              pip install --user --no-cache-dir huggingface_hub transformers torch timm
              python3 /mnt/scripts/download_virchow2.py
          env:
            - name: HOME
              value: /tmp
            - name: HF_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-secret
                  key: token
            - name: HTTPS_PROXY
              value: "http://proxy.ics.muni.cz:3128"
            - name: TORCH_HOME
              value: /tmp/torch
            - name: TORCHINDUCTOR_CACHE_DIR
              value: /tmp/torch/inductor_cache
          volumeMounts:
            - name: huggingface-cache
              mountPath: /mnt/huggingface_cache
            - name: scripts
              mountPath: /mnt/scripts
            - name: temp
              mountPath: /tmp
      restartPolicy: Never
      volumes:
        - name: huggingface-cache
          persistentVolumeClaim:
            claimName: huggingface-cache-pvc
        - name: scripts
          configMap:
            name: downloader-script
            defaultMode: 0755
        - name: temp
          emptyDir: {}
