workers:
  - cpu-workers
  - mig20-workers

applications:
  - episeg-1
  - heatmap-builder
  - prostate-classifier-1
  - prov-gigapath
  - virchow2

pvcs:
  storageClassName: nfs-csi
  huggingface:
    storage: 15Gi
    claimName: huggingface-cache-pvc
  tensorrtCache:
    storage: 20Gi
    claimName: tensorrt-cache-pvc
  data: data-ro
  publicData: rationai-data-ro-pvc-jobs
  projects: projects-rw
  biopticTree: bioptictree-ro
