workers:
  - cpu-workers
  - mig20-workers

applications:
  - episeg-1
  - heatmap-builder
  - prostate-classifier-1
  - prov-gigapath
  - virchow2

pvcs:
  storageClassName: nfs-csi
  huggingface:
    storage: 15Gi
    claimName: huggingface-cache-pvc
    mountPath: /mnt/huggingface_cache
  tensorrtCache:
    storage: 20Gi
    claimName: tensorrt-cache-pvc
    mountPath: /mnt/cache
  data:
    claimName: data-ro
    mountPath: /mnt/data
  publicData:
    claimName: rationai-data-ro-pvc-jobs
    mountPath: /mnt/data/Public
  projects:
    claimName: projects-rw
    mountPath: /mnt/projects
  biopticTree:
    claimName: bioptictree-ro
    mountPath: /mnt/bioptic_tree
