apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-model-test
spec:
  serveConfigV2: ""
  rayClusterConfig:
    rayVersion: 2.53.0
    enableInTreeAutoscaling: true
    autoscalerOptions:
      idleTimeoutSeconds: 60
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]

    headGroupSpec:
      rayStartParams:
        num-cpus: "0"
        dashboard-host: "0.0.0.0"
      template:
        spec:
          securityContext:
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          containers:
            - name: ray-head
              image: rayproject/ray:2.53.0-py312
              imagePullPolicy: Always
              resources:
                limits:
                  cpu: 0
                  memory: 4Gi
                requests:
                  cpu: 0
                  memory: 4Gi
              env:
                - name: HTTPS_PROXY
                  value: http://proxy.ics.muni.cz:3128
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
              securityContext:
                runAsUser: 1000
                allowPrivilegeEscalation: false
                capabilities:
                  drop: ["ALL"]

    workerGroupSpecs: []
