name: Build Documentation

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/build-docs.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "pyproject.toml"
      - "uv.lock"
      - ".github/workflows/build-docs.yml"

jobs:
  run:
    uses: RationAI/.github/.github/workflows/mkdocs-build.yml@main
